### ISSUE TITLE
crash shrinking a list (length on improper list)

### ISSUE THREAD

**Issue by samuelrivas** [proper-testing/proper#116]
Evaluating the next property crashes when trying to shrink the counterexample

``` Erlang
-module(proper_shrinking_gotcha).
-define(PROPER_NO_IMPORTS, true).
-define(PROPER_NO_TRANS, true).
-include_lib("proper/include/proper.hrl").
-compile(export_all).

permutation([]) ->
    [];
permutation(L) ->
    ?LET(E, proper_types:elements(L), [E | permutation(lists:delete(E, L))]).

bad_gen() ->
    G = proper_types:list(1),
    ?LET(Xs, G, permutation(Xs)).

prop_just_shrink() ->
    ?FORALL(L, bad_gen(), length(L) < 5).
```

The property is written so that it fails with a decently long list and is forced to shrink it:

```
1>  proper:quickcheck(proper_shrinking_gotcha:prop_just_shrink()).
.........!
Failed: After 10 test(s).
[1,1,1,1,1]

Shrinking ** exception error: bad argument
     in function  length/1
        called as length([1|{'$used',1,[1|{'$used',1,[1]}]}])
     in call from proper_types:fixed_list_test/2 (src/proper_types.erl, line 1052)
     in call from proper_types:is_instance/2 (src/proper_types.erl, line 446)
     in call from proper_types:is_instance/2 (src/proper_types.erl, line 441)
     in call from proper_types:is_instance/2 (src/proper_types.erl, line 446)
     in call from proper_types:is_instance/2 (src/proper_types.erl, line 441)
     in call from proper_types:is_instance/2 (src/proper_types.erl, line 446)
     in call from proper_types:is_instance/2 (src/proper_types.erl, line 441)
```

The macros to disable "proper magic" are probably irrelevant, I get the same result without them.

The generator passed to `proper_types:list/1` seems irrelevant too, but the generator passed to `permutation/1` needs to be `proper_types:list(Something)`. If I use this other generator for the property, shrinking works correctly:

```
good_gen() ->
    G = [1,2,3,4,5],
    ?LET(Xs, G, permutation(Xs)).
```

I reimplemented `permutation` in a different way to avoid the issue, so I don't worry about finding a solution for this code. I am reporting because it seems I triggered an inconsistency in proper.

This is tested with R16B03-1, proper 80c2c73

**Comment by ten0s** [comment]
I also faced the same issue. Here's the stacktrace:

Shrinking *failed*
in function erlang:length/1
  called as length([meta|{'$used',1186201588780,[1186201588780,1186204180780]}])
in call from proper_types:fixed_list_test/2 (src/proper_types.erl, line 1061)
in call from proper_types:is_instance/2 (src/proper_types.erl, line 448)
in call from lists:all/2 (lists.erl, line 1212)
in call from proper_types:is_instance/2 (src/proper_types.erl, line 448)
in call from lists:any/2 (lists.erl, line 1224)
in call from proper_types:is_instance/2 (src/proper_types.erl, line 448)
in call from proper_types:constructed_test/2 (src/proper_types.erl, line 473)
**error:badarg

The issue went away after I fixed the source problem, but without working shrinking it was difficult to find.
