### ISSUE TITLE
New Release?

### ISSUE THREAD

**Issue by ferd** [proper-testing/proper#176]
Hi,

I know I've asked for this a lot over the last few months, but I'm wondering when could we be expecting a new release (and a bump on the hex package as well)?

Since the last release (1.2.0) which was released in June 2016 (!!) it appears that the following improvements have been made to name a few:

- improving and simplifying multiple generators
- improving the performance of the framework overall
- color printouts
- `?SETUP` macro
- OTP-20 and OTP-21 support (I'm tired of these warnings!)
- added a basic map generator (albeit without support for type annotations-based generation)
- targeted properties
- other misc. bug fixes and lots of code cleanups, simplified build, etc.

I don't like being pushy, but I'd really like to be able to refer people to the hex package while being able to support all these improvements, or at the very least having a tag to avoid just telling them to "point it to master" or some specific hash.

**Comment by kostis** [comment]
Thanks for the prompt.

@TheGeorge :  do we have any pending changes to the manual / docs for the targeted stuff before I press the button for a 1.3.0 release?

**Comment by TheGeorge** [comment]
From my side you can go ahead and make a new release.

**Comment by kostis** [comment]
I've created a new 1.3.0 release (https://github.com/proper-testing/proper/releases).
If others can verify that it works OK for them then I will try to see how to also publish this to Hex.pm.
But since I've never done this before, some pointer(s) are appreciated.

PS. In the middle of vacations, hence the delay this period.

**Comment by ferd** [comment]
The release seems good to me. As for Hex.pm, there's usually someone who's owner of the lib on there, considering that they have published it already.

It appears @tsharju has current control of it. He could likely publish the new package for you, or hand control over to you. If you want control directly, you usually would have to write to support@hex.pm and they'll do some check for the ownership of the repo before transfering the rights.

To publish a package, there are a few changes to the .app file required. The documentation explaining it all is at https://hex.pm/docs/rebar3_publish -- just remember to have an up to date plugin and rebar3 to avoid most possible problems.

**Comment by getong** [comment]
@ferd @kostis 
The 1.3.0 tag is released, but not pushed to hex.pm? Would you do this?

**Comment by fenollp** [comment]
FYI I've been using f2b7b81666b21707244a40857cf50f4362b6e3c2 (commit of latest tag) for a while with no issue.

**Comment by getong** [comment]
Oh, I am sorry. I have send @tsharju  a email, I think there will be a good news.

**Comment by ferd** [comment]
Still no news from that packaging point of view. @kostis Would you like me to start asking the Hex folks for control of this repo for you, or would you be okay if someone in this issue took ownership of hex publication on your behalf?

**Comment by getong** [comment]
It is better to take control of this, and how can do it? Like the [poolboy](https://github.com/devinus/poolboy) , the new tag is made very days ago, but not pushed to hex.pm, just because not privilege granted.

**Comment by kostis** [comment]
> @kostis Would you like me to start asking the Hex folks for control of this repo for you, or would you be okay if someone in this issue took ownership of hex publication on your behalf?

I do not mind either way and, as I wrote above, any help / outsourcing of such tasks is appreciated.

@tsharju : if you read this, is it possible to push PropEr 1.3 into Hex.pm site and/or transfer the ownershop?

**Comment by tsharju** [comment]
I can definitely assist with the transfer. I’m not working with Elixir/Erlang atm so I’m not probably the right person to keep the package up-to-date.

**Comment by tsharju** [comment]
@ferd I added you as owner. Let me know if it worked. You can remove me from owners. I left myself there in case the transfer didn't work.

**Comment by ferd** [comment]
Alright, I published the new packcage. I'll close the issue.
