### ISSUE TITLE
proper_statem ?FORALL separate Erlang process execution?

### ISSUE THREAD

**Issue by okeuday** [proper-testing/proper#181]
I have ran into difficulties using the PropEr at the most recent commit (https://github.com/proper-testing/proper/commit/16f9f7cb181f41ffb882c4a31052275dfad16ee1) with `proper_statem` use that previously worked fine.  The failure hardly ever happens on `x86_64` (I saw it once or twice in Travis, and restarting the build made the test succeed, so it is a transient failure there) hardware for me.  However, when testing `s390x` architecture, it happens consistently.  It may be a bug in Erlang, but I wanted to check here.

The test is similar to http://proper.softlab.ntua.gr/Tutorials/PropEr_testing_of_generic_servers.html at https://github.com/okeuday/pqueue/blob/master/test/pqueue_proper.erl .  The failure is always similar to:
```
...........................................................!
Failed: After 3728 test(s).
[{set,{var,1},{call,cloudi_x_queue_srv,in,[-31]}},{set,{var,2},{call,cloudi_x_queue_srv,is_queue,[]}},{set,{var,3},{call,cloudi_x_queue_srv,in,[6]}},{set,{var,4},{call,cloudi_x_queue_srv,is_queue,[]}}]
History: []
State: {state,[]}
Result: {exception,exit,{noproc,{gen_server,call,[cloudi_x_queue_srv,{in,-31},infinity]}},[{gen_server,call,3,[{file,[103,101,110,95,115,101,114,118,101,114,46,101,114,108]},{line,223}]},{proper_statem,safe_apply,3,[{file,[115,114,99,47,112,114,111,112,101,114,95,115,116,97,116,101,109,46,101,114,108]},{line,581}]},{proper_statem,run_commands,5,[{file,[115,114,99,47,112,114,111,112,101,114,95,115,116,97,116,101,109,46,101,114,108]},{line,537}]},{proper_statem,run_commands,3,[{file,[115,114,99,47,112,114,111,112,101,114,95,115,116,97,116,101,109,46,101,114,108]},{line,506}]},{cloudi_x_pqueue_proper,'-correct/1-fun-2-',2,[{file,[116,101,115,116,47,99,108,111,117,100,105,95,120,95,112,113,117,101,117,101,95,112,114,111,112,101,114,46,101,114,108]},{line,81}]},{proper,apply_args,4,[{file,[115,114,99,47,112,114,111,112,101,114,46,101,114,108]},{line,1543}]},{proper,child,4,[{file,[115,114,99,47,112,114,111,112,101,114,46,101,114,108]},{line,1579}]},{proper,'-spawn_link_migrate/1-fun-1-',2,[{file,[115,114,99,47,112,114,111,112,101,114,46,101,114,108]},{line,743}]}]}
```
So, that means that somehow the `gen_server` being tested has its locally registered process die, and it is linked (by `gen_server:start_link`).  When unlinking the process after it is started but before the test begins, the start later is attempted a second time, so it appears that something in PropEr is attempting to call `start_link` more than once.  However, that would contradict the tutorial and the previous success of this PropEr test.

I have been using Erlang/OTP 21.1 for this testing.  Can you confirm that nothing is wrong with the approach at https://github.com/okeuday/pqueue/blob/master/test/pqueue_proper.erl ?  It is very similar to the tutorial and I do not see anything that seems wrong with the approach.

**Comment by okeuday** [comment]
I also have ran all the PropEr tests on the `s390x` instance, and they all pass:
```
dialyzer --build_plt --output_plt .plt/proper_plt --apps erts kernel stdlib compiler crypto syntax_tools
  Creating PLT .plt/proper_plt ...
Unknown functions:
  hipe:compile/4
 done in 3m4.12s
done (passed successfully)
dialyzer -n -nn --plt .plt/proper_plt -Wunmatched_returns ebin 
  Proceeding with analysis... done in 0m13.19s
done (passed successfully)
./make_doc
./rebar eunit
==> proper (eunit)
...
Compiled test/proper_tests.erl
  All 565 tests passed.
```

**Comment by kostis** [comment]
I've spent about half an hour trying to run the code in `pqueue_proper.erl`, but I got nowhere.  It is conceivable I am doing something stupid, but I will blame this on the quality of the above report anyway.

First I downloaded the above test file (`pqueue_proper.erl`) but quickly realized I also need the code to test.  Then I cloned the `pqueue` repository, but I could not locate the `queue_srv` module anywhere.
Thus, all my attempts to run the tests and try to reproduce and/or investigate this failed miserably with
<pre>
1> pqueue_proper:qc_pq().
!
Failed: After 1 test(s).
An exception was raised: error:undef.
Stacktrace: [{queue_srv,start_link,[pqueue],[]},
             {pqueue_proper,'-correct/1-fun-2-',2,
                            [{file,"pqueue_proper.erl"},{line,80}]}].
[{set,{var,1},{call,queue_srv,in,[0,-2]}}]

Shrinking .(1 time(s))
[]
false
</pre>

I am giving up.  Please submit either a list of commands to run (make sure you do not assume anything about my environment, not even that e.g. `rebar` is installed on my machine, because it is not) or a self-contained Erlang module that hopefully shows the problem you are experiencing.

**Comment by okeuday** [comment]
Sorry for not putting steps to reproduce.  I have been running PropEr on the `pqueue` repository as part of the CloudI eunit tests that are ran as part of the Travis build, though that is a slower way to test this failure.  However, that is why I haven't added `PropEr` as a dependency in the `rebar.config` file (keeping with rebar2 use to avoid incompatibility problems).

To reproduce with the `pqueue` repository (assuming PropEr was compiled in a location like `~/installed/packages/proper`), use:

    git clone https://github.com/okeuday/pqueue.git
    cd pqueue/
    rebar compile
    ERL_LIBS=~/installed/packages/proper rebar eunit

What you should see is eunit output like:
```
==> pqueue (eunit)
Compiled test/queue_srv.erl
Compiled test/pqueue_proper.erl
Compiled src/pqueue3.erl
Compiled src/pqueue2.erl
Compiled src/pqueue.erl
Compiled src/pqueue4.erl
  All 6 tests passed.
```
(on `x86_64`, `i686`, ARM, `ppc64` but not `s390x` which has the `noproc` failure for all PropEr tests after a variable number of tests and a variable amount of time)

**Comment by kostis** [comment]
Actually, I was able to locate the `queue_srv` module and test this during the night (here).  Unfortunately, I can only test this on x86_64.  In that platform, the problem you are reporting cannot be reproduced, even after running 1,000,000 tests (100 times more than what you typically run) which takes more that two hours to run (on my machine).
<pre>
1> pqueue_proper:qc_pq().
... 1000000 dots ...

OK: Passed 1000000 test(s).
 
11% {queue_srv,len,0}
11% {queue_srv,in,2}
11% {queue_srv,to_list,0}
11% {queue_srv,in,1}
11% {queue_srv,out,0}
11% {queue_srv,is_queue,0}
11% {queue_srv,pout,0}
11% {queue_srv,is_empty,0}
5% {queue_srv,out,1}
true
</pre>

Given the above and the information on your message above, I would blame the error you are experiencing on the (particular) `s390x` platform you are using.

**Comment by okeuday** [comment]
Thank you for checking it!  I will look further into problems with Erlang/`s390x` and testing specific to that.
