### ISSUE TITLE
`proper_statem` tutorial race condition with stop

### ISSUE THREAD

**Issue by okeuday** [proper-testing/proper#182]
This is a continuation of the https://github.com/proper-testing/proper/issues/181 issue with a focus on the source of the problem.  The tutorial at http://proper.softlab.ntua.gr/Tutorials/PropEr_testing_of_generic_servers.html has a race condition due to its use of `gen_server:call/3` to stop the `movie_server` (http://proper.softlab.ntua.gr/code/movies/movie_server.erl).  Instead, it should use `gen_server:stop/1` (a function added in Erlang/OTP 18.0 and probably newer than the tutorial).  Otherwise the locally registered name may still be used with a race to the next `gen_server:start_link/4` call due to the `gen_server:call/3`/stop-tuple approach not blocking until the Erlang process dies.

The problem was also discussed at https://bugs.erlang.org/browse/ERL-769 .

**Comment by kostis** [comment]
Thanks for investigating this deeper and reporting it here.
We have updated the code of `movie_server`.
Note, however, that the PropEr site has moved and is now hosted on GitHub (the ntua.gr one is still online, but updated less frequently).
