### ISSUE TITLE
The `cant_generate` error could include info about the failing constraints

### ISSUE THREAD

**Issue by robertoaloi** [proper-testing/proper#183]
When the random instance generation subsystem fails to produce an instance that satisfies some `?SUCHTHAT` constraint, a `cant_generate` error is returned to the user. The error indicates that the user should either increase the `constraint_tries` limits or loosen the failing constraints, but it does not contain any reference to the actual constraints which are failing. A hint could be provided to the user by analyzing the failing constraints, instead. In fact, the failing `Type` is already available to the `proper_gen:generate/3` function (see https://github.com/proper-testing/proper/blob/master/src/proper_gen.erl#L165) which throws the `cant_generate` exception, but it's discarded. The `Type` could instead be inspected, the constraints extracted (e.g. via `proper_types:get_prop(constraints, Type)` and further analyzed to return useful information (e.g. the module and the function name) about the constraint funs causing the failure (e.g. via `erlang:fun_info(F)`.

**Comment by kostis** [comment]
Thanks tor opening this issue!

Perhaps some concrete example(s) of failing `?SUCHTHAT` constraint generators and the info that one would like to see in that(those) case(s) would help us in doing something about that.

Even better, a PR on the subject is welcome!

**Comment by robertoaloi** [comment]
@kostis I just opened a PR which shows an example of a failing `?SUCHTHAT` and compares the current output with a possible alternative. As a note, the reason why I included the whole _Type_ at the end of the output is because it sometimes contains some useful hints to identify the root cause of the issue (usually as part of the `env` property. Any feedback or comment is welcome.

**Comment by kostis** [comment]
Fixed by #184
