### ISSUE TITLE
more_commands/2 does not generate more commands

### ISSUE THREAD

**Issue by alfert** [proper-testing/proper#192]
The size of the generated commands for a state machine via `commands/1` seems to depend on the `maximum_size`, as expected. According to the docs using `more_commands/2` should help here and generate more commands. But this does not seem to work. 

Example code: 
```erlang
-module(prop_sizedbug).
-include_lib("proper/include/proper.hrl").
-compile(export_all).

initial_state() -> ok.
    
command(_S) ->
    oneof([{call,?MODULE,foo,[integer()]},
	   {call,?MODULE,bar,[]}]).

precondition(_, _) -> true.
next_state(_, _, _) -> ok.
postcondition(_, _, _) -> true.

foo(_I) -> ok.
bar() -> 42.

prop_simple() ->
    ?FORALL(Cmds, commands(?MODULE),
        measure("Length of Cmds", length(Cmds), length(Cmds) >= 0)).

prop_more() ->
    ?FORALL(Cmds, more_commands(20, commands(?MODULE) ),
        measure("Length of Cmds", length(Cmds), length(Cmds) >= 0)).
```

Result from running `rebar3 proper` is 
```
===> Testing prop_sizedbug:prop_simple()
....................................................................................................
OK: Passed 100 test(s).

Length of Cmds
minimum: 0
average: 10.34
maximum: 36
===> Testing prop_sizedbug:prop_more()
....................................................................................................
OK: Passed 100 test(s).

Length of Cmds
minimum: 0
average: 10.18
maximum: 38
===> 
2/2 properties passed
```

For `prop_more()` I expected that something upto 800 commands would be generated in the command list. Setting the `max_size` does helps here, but still `more_commands/2` has no effect.

**Comment by TheGeorge** [comment]
I just checked the code and resize does not propagate to ?SIZED generators (which commands is) further along. Instead the the base size is read again making more_commands not work properly.

**Comment by TheGeorge** [comment]
Actually, resize seems to only have local affect directly on the generator it is invoked on.
