### ISSUE TITLE
Substitute uses of `slave` with `peer`

### ISSUE THREAD

**Issue by kostis** [proper-testing/proper#293]
Erlang/OTP 25.0 introduces the following warnings about the `slave` module becoming deprecated in two years:

```
proper.erl:2407:10: Warning: slave:start_link/2 is deprecated and will be removed in OTP 27; use the 'peer' module instead
% 2407|     case slave:start_link(HostName, SlaveName) of

proper.erl:2479:64: Warning: slave:stop/1 is deprecated and will be removed in OTP 27; use the 'peer' module instead
% 2479|             StopFun = fun({Node, {already_running, false}}) -> slave:stop(Node);
```

Thus, I am creating this issue, which obviously is not urgent (esp. since PropEr still supports Erlang/OTP versions where the `peer` module is not present) so that somebody looks into this.  @pablocostass perhaps?

**Comment by pablocostass** [comment]
Hey @kostis, I will gladly take a look at this this week, I knew this was bound to happen at some point. I seem to remember that the new `peer` module introduced in OTP25 has a bit of a different API than the deprecated module had, but it should not require many changes :)
